### ISSUE TITLE
Don't use the \Contao\* namespace

### ISSUE THREAD

**Issue by stefanheimes** [unmaintained-stuff/httprequestextended#9]
$objIdn = new \Contao\Idna(); <= This kills the contao autoload.

Don't use the Contao namespace, only the root namespace. So \Contao\Idna is wrong or better say kills the system. Only use the root namespace \Idna. 

Why? 

If you call \Contao\Idna and another one calls the simple  \Idna the autoload trys to load the \Contao\Idna and than the class \Idna. But it is the same class so you got a 

``` php
 Fatal error: include(): Cannot redeclare class contao\idna in [...]/system/modules/core/library/Contao/ClassLoader.php on line 163 
```

**Comment by discordier** [comment]
Confirmed. Must have been overseen in your PR. Do you want to file a PR?

**Comment by discordier** [comment]
Closing as this repository is unmaintained now. I suggest to switch to guzzle or any other `php-http` implementation. See [http://httplug.io/](http://httplug.io/).
